apiVersion: gcp.platform.upbound.io/v1alpha1
kind: XGKE
metadata:
  name: configuration-gcp-gke-castai
spec:
  parameters:
    id: configuration-gcp-gke-castai
    region: us-west2
    version: latest
    nodes:
      count: 1
      instanceType: n1-standard-4
  writeConnectionSecretToRef:
    name: configuration-gcp-gke-castai-kubeconfig
    namespace: upbound-system
